on: [push]
name: Build ProxyDialogAutoFiller
jobs:
  build:
    runs-on: [ windows-2022 ]
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Compile
        run: msbuild /p:Configuration=Release /p:Platform="Any CPU"
      - name: Make Installer
        run: iscc.exe ProxyDialogAutoFiller.iss
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: |
            bin/Release/*.exe
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Installers
          path: SetupOutput/*.exe